/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisador1;

import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author avnel
 */
public class Analisador1_1 extends javax.swing.JFrame {

    /**
     * Creates new form Analisador1_1
     */
    public Analisador1_1() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto = new javax.swing.JTextField();
        verificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        verificar.setText("verificar");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane2.setViewportView(resultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(verificar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(verificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        // TODO add your handling code here:
        String expresion = texto.getText();
        String patron = ("([while | for | if ]+)|([a-zA-Z]+)|([>|<|=|+|*|-]+)|([0-9]+)|([(|)]+)|([{|}]+)|(:)");
        String reservada="",variable="",operador="",numero="",parentisis="",llave="",fin="";
        
        Pattern p = Pattern.compile(patron);
        Matcher matcher = p.matcher(expresion);
        String tokenTipo1;
        String tokenTipo2;
        String tokenTipo3;
        String tokenTipo4;
        String tokenTipo5;
        String tokenTipo6;
        String tokenTipo7;
        int i=0;
        while(matcher.find())
        {//System.out.println(i++);
             tokenTipo1 = matcher.group(1);
             
            if(tokenTipo1!= null)
            {
                reservada+=tokenTipo1+" ";
                System.out.println("no debio entrar");
            }  
              tokenTipo2 = matcher.group(2);
            if(tokenTipo2!= null)
            {    
               variable+=tokenTipo2+" ";
               //System.out.println(variable);
            }  
             tokenTipo3 = matcher.group(3);
            if(tokenTipo3!= null)
               {
                 operador+= tokenTipo3+" ";
                 //System.out.println(operador);
               }
             tokenTipo4 = matcher.group(4);
            if(tokenTipo4!= null)
             {
                numero+= tokenTipo4+" ";
                //System.out.println(numero);
             }
             tokenTipo5 = matcher.group(5);
            if(tokenTipo5!= null)
            {
                parentisis+=tokenTipo5+" ";
                //System.out.println(parentisis);
            }
             tokenTipo6 = matcher.group(6);
            if(tokenTipo6!= null)
            {
                 llave+= tokenTipo6+" ";
                 //System.out.println(llave);
            }
             tokenTipo7 = matcher.group(7);
            if(tokenTipo7!= null)
             {
                  fin+= tokenTipo7+" ";
                  //System.out.println(fin);
             }
            
        } 
        String imprime="";
        if(!reservada.equals(""))
        imprime+="Palabra reservada "+reservada +"\n";
        if(!variable.equals(""))
        imprime+="variables " +variable +"\n";
        if(!operador.equals(""))
        imprime +="operador " +operador +"\n";
        if(!numero.equals(""))
        imprime+= "numero " +numero +"\n";
        if(!parentisis.equals(""))
        imprime +="parentesis " +parentisis +"\n";
        if(!llave.equals(""))
       imprime += "llave " +llave +"\n";
        if(!fin.equals(""))
        imprime+= "fin " +fin +"\n";
        
        resultado.setText(imprime);
        
        
        
        
    }//GEN-LAST:event_verificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analisador1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analisador1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analisador1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analisador1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analisador1_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField texto;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
